# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [2]:
def softmax(x):
    """
    对输入的张量进行softmax操作。

    参数：
    x：输入的张量

    返回值：
    prob_x：经过softmax操作后的概率分布张量
    """
    # 对输入张量中的每个元素求指数函数
    exp_x = tf.exp(x - tf.reduce_max(x, axis=-1, keepdims=True))

    # 对指数函数结果进行归一化处理，得到概率分布
    prob_x = exp_x / tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    
    return prob_x


test_data = np.random.normal(size=[10, 5])

(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [3]:
def sigmoid(x):
    """
    对输入的张量进行sigmoid操作。

    参数：
    x：输入的张量

    返回值：
    prob_x：经过sigmoid操作后的概率分布张量
    """
    # 计算sigmoid函数值
    prob_x = 1 / (1 + tf.exp(-x))
    return prob_x


test_data = np.random.normal(size=[10, 5])


(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [4]:
def softmax_ce(x, label):
    """
    计算softmax交叉熵损失函数。

    参数：
    x：模型的输出概率分布张量
    label：实际标签的独热编码张量

    返回值：
    loss：softmax交叉熵损失值
    """
    # 计算交叉熵损失
    loss = -tf.reduce_mean(tf.reduce_sum(label * tf.math.log(x), axis=-1))

    return loss


test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)


label = np.zeros_like(test_data)


label[np.arange(10), np.random.randint(0, 5, size=10)]=1.



((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))


  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [5]:
def sigmoid_ce(x, label):
    """
    计算sigmoid交叉熵损失函数。

    参数：
    x：模型的输出概率分布张量
    label：实际标签的独热编码张量

    返回值：
    loss：sigmoid交叉熵损失值
    """
    # 计算交叉熵损失
    loss = -tf.reduce_mean(label * tf.math.log(x) +
                           (1-label) * tf.math.log(1-x))

    return loss



test_data = np.random.normal(size=[10])


prob = tf.nn.sigmoid(test_data)


label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)



((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()

[0. 0. 1. 1. 1. 1. 0. 0. 0. 1.]


True